CadastroGeral/Controllers/AlterarSenhaController.cs
using CadastroGeral.Interfaces;
using CadastroGeral.Models;
using Microsoft.AspNetCore.Mvc;

namespace CadastroGeral.Controllers
{
    public class AlterarSenhaController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly ISessaoUsuario _sessaoUsuario;
        //private readonly ISessaoMembro _sessaoMembro;

        public AlterarSenhaController(
            IUsuarioRepositorio usuarioRepositorio,
            ISessaoUsuario sessaoUsuario)//,
            //ISessaoMembro sessaoMembro)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _sessaoUsuario = sessaoUsuario;
            //_sessaoMembro = sessaoMembro;
        }


        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Alterar(AlterarSenhaModel alterarSenhaModel)
        {
            try
            {
                //pegando usuário logado
                UsuarioModel usuarioLogado = _sessaoUsuario.BuscarSessaoUsuario();
                alterarSenhaModel.Id = usuarioLogado.Id;

                ////pegando membro logado
                //MembroModel membroLogado = _sessaoMembro.BuscarSessaoMembro();
                //alterarSenhaModel.Id = membroLogado.Id;


                if(ModelState.IsValid)
                {
                    _usuarioRepositorio.AlterarSenha(alterarSenhaModel);
                    TempData["MensagemSucesso"] = "Senha alterada com sucesso!";
                    return View("Index", alterarSenhaModel);
                }

                return View("Index", alterarSenhaModel);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos alterar sua senha, tente novamente, detalhes do erro: {erro.Message}";
                return View("Index", alterarSenhaModel);
            }
        }
    }
}

CadastroGeral/Views/AlterarSenha/Index.cshtml
@using CadastroGeral.Enums
@model AlterarSenhaModel

@{ViewData["Title"] = "Alterar Senha do Usuário";}

<div class="text-center">
    <h1 class="display-4">Alterar Senha do Usuário</h1>
</div>

<!--Mensagem de sucesso-->
@if(TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
 }
  
 <!--Mensagem de erro-->
@if(TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
        @TempData["MensagemErro"]
    </div>
 }

<form asp-controller="AlterarSenha" asp-action="Alterar" method="post">

    <div class="form-group">
        <label asp-for="SenhaAtual">Senha Atual</label>
        <input type="password" asp-for="SenhaAtual" class="form-control" placeholder="Digite a senha atual do usuário!">
        @Html.ValidationMessageFor(x => x.SenhaAtual)    
    </div>

    <div class="form-group">
        <label asp-for="NovaSenha">Nova Senha</label>
        <input type="password" asp-for="NovaSenha" class="form-control" placeholder="Digite a nova senha do usuário!">
        @Html.ValidationMessageFor(x => x.NovaSenha)    
    </div>

    <div class="form-group">
        <label asp-for="ConfirmarNovaSenha">Confirmar Nova Senha</label>
        <input type="password" asp-for="ConfirmarNovaSenha" class="form-control" placeholder="Confirme a nova senha usuário!">
        @Html.ValidationMessageFor(x => x.ConfirmarNovaSenha)    
    </div>

    <br />

<button type="submit" class="btn btn-primary btn-block">Alterar</button>
<a class="btn btn-secondary" asp-controller="Home" asp-action="Index" role="button"> Voltar</a>
</form>